"""add prescription storage keys and reconciliation support

Revision ID: 3316d21169ca
Revises: f1a2b3c4d5e6
Create Date: 2026-09-27 15:16:00.376987

Three changes, and two of them Alembic cannot produce on its own:

1. ``prescriptions.storage_key`` -- the opaque storage key, separate from
   ``file_url``. Added as nullable, backfilled, then tightened, because
   PostgreSQL cannot add a NOT NULL column to a table that already has rows.
2. ``duplicate_flags.resolved_at`` -- when a flag was answered. Plain addition.
3. ``ALTER TYPE medicine_status ADD VALUE 'rejected'`` -- Alembic has no
   autogenerate support for adding a value to a native PostgreSQL enum, so this
   is written by hand. If it is ever autogenerated away, ``rejected`` silently
   becomes un-insertable at runtime rather than failing at deploy time.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3316d21169ca"
down_revision: str | None = "f1a2b3c4d5e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Length of the public mount prefix, '/files/'. Backfill strips exactly this
# many leading characters to recover the storage key from a local-backend URL.
_URL_PREFIX_LEN = len("/files/") + 1


def upgrade() -> None:
    # --- 1. prescriptions.storage_key -------------------------------------
    # Nullable first. A single `ADD COLUMN ... NOT NULL` fails outright on any
    # table with existing rows, so the constraint is applied after the backfill.
    op.add_column(
        "prescriptions",
        sa.Column("storage_key", sa.String(length=512), nullable=True),
    )

    # Recover the key from the URL the local backend already wrote:
    # '/files/prescriptions/7/<uuid>.pdf' -> 'prescriptions/7/<uuid>.pdf'.
    # Rows whose URL has some other shape cannot be attributed to a real key, so
    # they get an explicit 'legacy/' marker rather than a fabricated path. That
    # marker is deliberately not a valid storage key: a delete against it will
    # fail the traversal check in LocalStorageService rather than remove
    # something arbitrary.
    op.execute(
        sa.text(
            """
            UPDATE prescriptions
               SET storage_key = CASE
                       WHEN file_url LIKE '/files/%'
                           THEN substr(file_url, :prefix_len)
                       ELSE 'legacy/' || id::text
                   END
             WHERE storage_key IS NULL
            """
        ).bindparams(prefix_len=_URL_PREFIX_LEN)
    )

    op.alter_column(
        "prescriptions", "storage_key", nullable=False, existing_type=sa.String(512)
    )

    # --- 2. duplicate_flags.resolved_at ------------------------------------
    op.add_column(
        "duplicate_flags",
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    )

    # --- 3. medicine_status gains 'rejected' -------------------------------
    # IF NOT EXISTS so re-running against a partially-migrated database is a
    # no-op rather than a crash. Safe inside the transaction Alembic opens:
    # PostgreSQL 12+ allows ADD VALUE there, and nothing in this migration uses
    # the new value, which is the only real restriction.
    op.execute("ALTER TYPE medicine_status ADD VALUE IF NOT EXISTS 'rejected'")


def downgrade() -> None:
    op.drop_column("duplicate_flags", "resolved_at")
    op.drop_column("prescriptions", "storage_key")

    # --- remove 'rejected' from medicine_status -----------------------------
    # PostgreSQL 16 has no `ALTER TYPE ... DROP VALUE`; that syntax arrived in
    # 17. On 16 the only way to drop an enum label is to rebuild the type, which
    # is what follows. It is safe here specifically because the type is used in
    # exactly one place (`medicines.status`) with no index and no CHECK
    # constraint on it -- both were verified before writing this. If someone
    # later indexes that column, this block needs the index recreated too.
    #
    # Side effect: `status` moves to the end of the table's column order. Purely
    # cosmetic, and only on the way down.
    op.execute(
        """
        DO $$
        BEGIN
            -- Already free of the value (a no-op downgrade, or a partial run).
            IF NOT EXISTS (
                SELECT 1 FROM pg_type t
                JOIN pg_enum e ON e.enumtypid = t.oid
                WHERE t.typname = 'medicine_status' AND e.enumlabel = 'rejected'
            ) THEN
                RETURN;
            END IF;

            -- No row may still hold the value, or the type rebuild below fails.
            -- Rejected and active are different facts, but the row is about to
            -- be reopened by this downgrade anyway, so 'active' is the landing
            -- spot that loses the least information.
            UPDATE medicines SET status = 'active' WHERE status = 'rejected';

            ALTER TYPE medicine_status RENAME TO medicine_status_old;
            CREATE TYPE medicine_status AS ENUM ('active', 'discontinued');
            ALTER TABLE medicines DROP COLUMN status;
            ALTER TABLE medicines
                ADD COLUMN status medicine_status NOT NULL DEFAULT 'active';
            DROP TYPE medicine_status_old;
        END $$;
        """
    )
